### ISSUE TITLE
Allow separate save directories for multiple installs of one mod

### ISSUE THREAD

**Issue by Kizby** [GanstaKingofSA/DDML#13]
If I use this launcher to install a mod multiple times (e.g. so multiple people can play separately from one user account), I'd like the saves for those installs to be separate as well. Currently, any installation of mod `$build.name` stores its saves in `$APPDATA/RenPy/$build.name`, so each separate installation sees the same set of saves. Specifically, I'm running Club Meetings Season 1 right now and seeing this behavior.

I suspect I'll dig in and put together a PR for this before too long, but I suspect you know way better than I do how renpy saving works and maybe this would be a quick thing?

**Comment by Bronya-Rand** [comment]
Closed due to sunsetting and new work on Mod Docker as stated in README and PR #14
