### ISSUE TITLE
DDML fails to properly install the Purist Mod

### ISSUE THREAD

**Issue by AshenPaladin** [GanstaKingofSA/DDML#15]
**Describe the bug**
DDML fails to properly install the Purist Mod.

**To Reproduce**
1. Select "Add a mod"
2. Input the mod name
3. Select the Purist mod 1.1 version zip file
4. Attempt to launch the mod
5. See the regular game launch

**Expected behavior**
The launcher should normally be able to launch and to install the mod, all other mods that I've tried work so it might be an issue with the zip file itself

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Mod: DDLC Purist Mod
 - DDML Version 5.3.1.

**Additional context**
I think that the practical issue is that the mod launcher does not install the files within the zip in the "game" folder as the DDLC Purist mod install instructions seem to indicate. Manually dragging and dropping the files of the Purist zip within the "game" folder of the game installation created by the DDML allows it to properly work without any issues.

**Comment by Bronya-Rand** [comment]
Hi and thanks for reporting the issue.

Looks like the install method doesn't work well with Purist Mod and while I planned to check it and see this, I have decided to sunset DDML in favor of the new Doki Doki Mod Docker project I have been working on instead which should bring more better compatibility than normal. This issue will now be closed but you may try Mod Docker out for better results.
